routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|


Route::get('/', function () {
    return view('welcome');
});*/


use App\Http\Controllers\ScoreController;
 
Route::resource('scores', ScoreController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/score.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Score extends Model
{
    //use HasFactory;
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ScoreController.php
<?php

namespace App\Http\Controllers;

use \App\Models\Score;

use Illuminate\Http\Request;

class ScoreController extends Controller
{
/**
* Display a listing of the resource.
*
* @return \Illuminate\Http\Response
*/
public function index(){
    $data['scores'] = Score::orderBy('id')->paginate(5);
    return view('scores.index', $data);
}
    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
public function create(){
    return view('scores.create');
}
    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
public function store(Request $request){
    $request->validate([
        'name' => 'required',
        'g1' => 'required',
        'g2' => 'required',
        'g3' => 'required',
    ]);
    $score = new Score;
    $score->name = $request->name;
    $score->g1 = $request->g1;
    $score->g2 = $request->g2;
    $score->g3 = $request->g3;
    $score->total = $score->g1 + $score->g2 + $score->g3;
    $score->save();
    return redirect()->route('scores.index')->with('success','score has been created successfully.');
}
    /**
    * Display the specified resource.
    *
    * @param  \App\Score  $score
    * @return \Illuminate\Http\Response
    */
public function show(Score $score){
    return view('scores.show',compact('score'));
} 
    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Score  $score
    * @return \Illuminate\Http\Response
    */
public function edit(Score $score){
    return view('scores.edit',compact('score'));
}
    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Score  $score
    * @return \Illuminate\Http\Response
    */
public function update(Request $request, $id){
    $request->validate([
        'name' => 'required',
        'g1' => 'required',
        'g2' => 'required',
        'g3' => 'required',
        /*'name' => 'required',
        'email' => 'required',
        'address' => 'required',
        'serial' => 'required',*/
    ]);
    $score = Score::find($id);
    $score->name = $request->name;
    $score->g1 = $request->g1;
    $score->g2 = $request->g2;
    $score->g3 = $request->g3;
    $score->total = $score->g1 + $score->g2 + $score->g3;
    $score->save();
    return redirect()->route('scores.index')->with('success','score Has Been updated successfully');
}
    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Score  $score
    * @return \Illuminate\Http\Response
    */
public function destroy(Score $score)
{
    $score->delete();
    return redirect()->route('scores.index')->with('success','score has been deleted successfully');
}
}

resources/views/scores/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add score Form - Laravel 9 CRUD</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body>
    <div class="container mt-2">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left mb-2">
                    <h2>Add score</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('scores.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if(session('status'))
    <div class="alert alert-success mb-1 mt-1">
    {{ session('status') }}
    </div>
    @endif
    <form action="{{ route('scores.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>score Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="score Name">
                @error('name')
                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>score g1:</strong>
                <input type="g1" name="g1" class="form-control" placeholder="score g1">
                @error('g1')
                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>score g2:</strong>
                <input type="text" name="g2" class="form-control" placeholder="score g2">
                @error('g2')
                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>score g3:</strong>
                <input type="text" name="g3" class="form-control" placeholder="score g3">
                @error('g3')
                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <button type="submit" class="btn btn-primary ml-3">Submit</button>
    </div>
    </form>
</body>
</html>

resources/views/scores/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit score Form - Laravel 9 CRUD Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body>
    <div class="container mt-2">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Edit score</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('scores.index') }}" enctype="multipart/form-data"> Back</a>
                </div>
            </div>
        </div>
        @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
            {{ session('status') }}
        </div>
        @endif
        <form action="{{ route('scores.update',$score->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>score Name:</strong>
                    <input type="text" name="name" value="{{ $score->name }}" class="form-control" placeholder="score name">
                    @error('name')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>score g1:</strong>
                    <input type="g1" name="g1" class="form-control" placeholder="score g1" value="{{ $score->g1 }}">
                    @error('g1')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>score g2:</strong>
                    <input type="text" name="g2" value="{{ $score->g2 }}" class="form-control" placeholder="score g2">
                    @error('g2')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>score g3:</strong>
                    <input type="text" name="g3" value="{{ $score->g3 }}" class="form-control" placeholder="score g3">
                    @error('serial')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <button type="submit" class="btn btn-primary ml-3">Submit</button>
        </div>
        </form>
    </div>
</body>
</html>

resources/views/scores/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Laravel 9 CRUD</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body>
    <div class="container pt-5">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>LARAVEL SCORE</h2>
                </div>
                <div class="pull-right mb-2">
                    <a class="btn btn-primary" href="{{ route('scores.create') }}"> CREATE SCORE</a>
                </div>
            </div>
        </div>
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <style>{
            .table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
                background-color: #blue;
            }

            }
            </style>
        <table class="table table-striped table-hover">
            <thead class= "thead-dark">
                <tr>
                    <th>#</th>
                    <th>NAME</th>
                    <th>SCORE 1</th>
                    <th>SCORE 2</th>
                    <th>SCORE 3</th>
                    <th>TOTAL</th>
                    <th width="200px">ACTION</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($scores as $score)
                <tr>
                    <th scope="row">{{ $score->id }}</td>
                    <td>{{ strtoupper($score->name) }}</td>
                    <td>{{ $score->g1 }}</td>
                    <td>{{ $score->g2 }}</td>
                    <td>{{ $score->g3 }}</td>
                    <td>{{ $score->total}}</td>
                    <td>
                        <form action="{{ route('scores.destroy',$score->id) }}" method="Post">
                        <a class="btn btn-warning" href="{{ route('scores.edit',$score->id) }}">EDIT</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">DELETE</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <?php include 'C:\Users\User\OneDrive\Desktop\Dev\Laravel\mysqlcalc\app\Service\total.php';?>
    {!! $scores->links() !!}
</body>
</html>